# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5845b7dc340c36f641c22b4ffa324038eb8773e540db2e9c0e1271c27c1afb97cf14c462bfc1aba0a2cf763cbea6dea584cd5a1e0d05a98ed8bff3ebefd4b648

test:
  secret_key_base: 0f3dcdc0fd84db4b81290f95e3834f8e27376fd1c918969c8ea17ec85b4545afa22e2769e48d114c70af93b28ea13eb46558aeb26a564751cd9fecceee822b9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
